#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A project.asgi.celery inspect ping
}

until worker_ready; do
    echo >&2 'Celery workers not available'
    sleep 1
done
echo >&2 'Celery workers is available'

exec celery flower \
    --app=project.asgi.celery \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
