#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A main.celery inspect ping
}

until worker_ready; do
    echo >&2 'Celery workers not available'
    sleep 1
done
echo >&2 'Celery workers is available'

celery flower \
    --app=main.celery \
    --broker="${CELERY_BROKER_URL}"
